### ISSUE TITLE
Guideline of forum

### ISSUE THREAD

**Issue by Miachol** [JhuangLab/BioInstaller#11]
## Introduction

The main aim of this forum is to provide a fully free place sharing the bioinformatics tools/scripts and databases. The resources recorded in the posts will be integrated in the BioInstaller configuration files. Please read this post firstly when you want to submit a new post in this forum.

## Acceptable posts

- Any bioinformatics related papers
- Any bioinformatics related tools/scripts and databases (Both open and restricted)
- Suggestions for improving this community
- Bug report

## Reference format for uploading new BioInstaller items

Configuration file: (github.toml, nongithub.toml, db_annovar.toml, db_main.toml, or new)
Description: Summary of the tools/scripts and databases

```toml
[snakemake_dna_gatk_flow]
github_url = "https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling"
```
