### ISSUE TITLE
Share protein function analysis related

### ISSUE THREAD

**Issue by Miachol** [JhuangLab/BioInstaller#16]
Configuration file: nongithub.toml
Description:  effusion, A method for predicting protein function, Effusion, that uses a sequence similarity network to add context for homology transfer, a probabilistic model to account for the uncertainty in labels and function propagation, and the structure of the Gene Ontology (GO) to best utilize sparse input labels and make consistent output predictions. Effusion's model makes it practical to integrate rare experimental data and abundant primary sequence and sequence similarity.
Publication: Effusion: Prediction of Protein Function from Sequence Similarity Networks. Bioinformatics. 2018 Aug 01, PMID: 30084920 DOI: 10.1093/bioinformatics/bty672

```toml
[effusion]
source_url = "http://www.babbittlab.ucsf.edu/effusion/effusion_{{version}}.tar.gz"
version_available = ["1.0.0"]
```
