### ISSUE TITLE
Upload snakemake-workflows/dna-seq-gatk-variant-calling

### ISSUE THREAD

**Issue by Miachol** [JhuangLab/BioInstaller#8]
Configuration file: github.toml

```toml
[snakemake_dna_gatk_flow]
description = "This Snakemake pipeline implements the GATK best-practices workflow"
source_url = "https://github.com/snakemake-workflows/dna-seq-gatk-variant-calling"
```
