### ISSUE TITLE
Share deep learning based methods

### ISSUE THREAD

**Issue by Miachol** [JhuangLab/BioInstaller#9]
Configuration file: github.toml
Description: "mRNN is an implementation of a Gated Recurrent Unit (GRU) network for classification of transcripts as either coding or noncoding."

```toml
[mrnn]
github_url = https://github.com/hendrixlab/mRNN
```
